languageCode = "en-us"
title = "Chris I Powell"
baseURL = "https://www.chrisipowell.co.uk/"
theme = "chrisipowell"

googleAnalytics = "UA-65763968-1"
DisqusShortname = "chrisipowell"

[Params]
  rss = true
  comments = true
  DisqusShortname = "chrisipowell"

[Author]
  name = "Chris I Powell"
  github = "CIPowell"
  twitter = "ChrisIPowell"
  linkedin = "chris-i-powell"
